apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdfrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jdfrs
  template:
    metadata:
      labels:
        app: jdfrs
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vless_Path
          value: "/vdhd5"
        - name: Vmess_UUID
          value: "72398242-d14b-441c-a96e-d242738237a5"
        - name: Vmess_Path
          value: "/vdhd5"
        - name: Share_Path
          value: "/v2link"
